variant = "loose"

[[issues]]
file = "src/CoreRoutingMiddleware.php"
code = "impossible-assignment"
message = "Invalid assignment: the right-hand side has type `never` and cannot produce a value."
count = 1

[[issues]]
file = "src/CoreRoutingMiddleware.php"
code = "impossible-condition"
message = "This condition (type `false`) will always evaluate to false."
count = 1

[[issues]]
file = "src/CoreRoutingMiddleware.php"
code = "invalid-method-access"
message = 'Attempting to access a method on a non-object type (`unknown-ref(Waffle\Commons\Contracts\Routing\RouterInterface)`).'
count = 1

[[issues]]
file = "src/CoreRoutingMiddleware.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 1

[[issues]]
file = "src/CoreRoutingMiddleware.php"
code = "no-value"
message = 'Argument #2 passed to method `Psr\Http\Message\ServerRequestInterface::withattribute` has type `never`, meaning it cannot produce a value.'
count = 5

[[issues]]
file = "src/CoreRoutingMiddleware.php"
code = "non-existent-catch-type"
message = 'Attempting to catch an undefined class or interface: `Waffle\Commons\Contracts\Routing\Exception\RouteNotFoundExceptionInterface`.'
count = 1

[[issues]]
file = "src/CoreRoutingMiddleware.php"
code = "non-existent-class-like"
message = 'Class, interface, enum, or trait `Waffle\Commons\Contracts\Constant\Constant` not found.'
count = 6

[[issues]]
file = "src/CoreRoutingMiddleware.php"
code = "redundant-comparison"
message = "Redundant `===` comparison: left-hand side is never identical to right-hand side."
count = 1

[[issues]]
file = "src/CoreRoutingMiddleware.php"
code = "unevaluated-code"
message = "Unreachable code detected."
count = 1

[[issues]]
file = "src/CoreRoutingMiddleware.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `RuntimeException` in `Waffle\Commons\Pipeline\CoreRoutingMiddleware::process`.'
count = 1

[[issues]]
file = "src/MiddlewareStack.php"
code = "non-existent-class-like"
message = 'Class `Waffle\Commons\Pipeline\MiddlewareStack` cannot implement unknown type `MiddlewareStackInterface`'
count = 1

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "invalid-argument"
message = '''Invalid argument type for argument #1 of `phpunit\framework\testcase::expectexception`: expected `class-string<Throwable>`, but found `class-string('Waffle\Commons\Contracts\Routing\Exception\RouteNotFoundExceptionInterface')`.'''
count = 1

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "invalid-argument"
message = 'Invalid argument type for argument #1 of `waffle\commons\pipeline\coreroutingmiddleware::__construct`: expected `unknown-ref(Waffle\Commons\Contracts\Routing\RouterInterface)`, but found `PHPUnit\Framework\MockObject\MockObject&Waffle\Commons\Contracts\Routing\RouterInterface`.'
count = 4

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "mixed-method-access"
message = "Attempting to access a method on a non-object type (`mixed`)."
count = 9

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "no-value"
message = 'Argument #2 passed to method `PHPUnit\Framework\MockObject\InvocationStubber::with` has type `never`, meaning it cannot produce a value.'
count = 6

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "non-existent-class-like"
message = "Class `class@anonymous:10703952525790376349-7861:7941` cannot implement unknown type `RouteNotFoundExceptionInterface`"
count = 1

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "non-existent-class-like"
message = 'Class, Interface, or Trait `Waffle\Commons\Contracts\Routing\RouterInterface` does not exist.'
count = 8

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "non-existent-class-like"
message = 'Class, interface, enum, or trait `Waffle\Commons\Contracts\Constant\Constant` not found.'
count = 18

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `WaffleTests\Commons\Pipeline\CoreRoutingMiddlewareTest::testItBubblesExceptionWhenRouteNotFound`.'
count = 1

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `WaffleTests\Commons\Pipeline\CoreRoutingMiddlewareTest::testItHandlesRouteWithoutOptionalParams`.'
count = 1

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `WaffleTests\Commons\Pipeline\CoreRoutingMiddlewareTest::testItMatchesRouteAndEnrichesRequest`.'
count = 1

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `WaffleTests\Commons\Pipeline\CoreRoutingMiddlewareTest::testItThrowsRuntimeExceptionWhenRouterReturnsNull`.'
count = 1

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\ExpectationFailedException` in `WaffleTests\Commons\Pipeline\CoreRoutingMiddlewareTest::testItMatchesRouteAndEnrichesRequest`.'
count = 1

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `WaffleTests\Commons\Pipeline\CoreRoutingMiddlewareTest::testItBubblesExceptionWhenRouteNotFound`.'
count = 1

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `WaffleTests\Commons\Pipeline\CoreRoutingMiddlewareTest::testItHandlesRouteWithoutOptionalParams`.'
count = 1

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `WaffleTests\Commons\Pipeline\CoreRoutingMiddlewareTest::testItMatchesRouteAndEnrichesRequest`.'
count = 1

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `WaffleTests\Commons\Pipeline\CoreRoutingMiddlewareTest::testItThrowsRuntimeExceptionWhenRouterReturnsNull`.'
count = 1

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `WaffleTests\Commons\Pipeline\CoreRoutingMiddlewareTest::testItBubblesExceptionWhenRouteNotFound`.'
count = 1

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `WaffleTests\Commons\Pipeline\CoreRoutingMiddlewareTest::testItHandlesRouteWithoutOptionalParams`.'
count = 1

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `WaffleTests\Commons\Pipeline\CoreRoutingMiddlewareTest::testItMatchesRouteAndEnrichesRequest`.'
count = 1

[[issues]]
file = "tests/src/CoreRoutingMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `WaffleTests\Commons\Pipeline\CoreRoutingMiddlewareTest::testItThrowsRuntimeExceptionWhenRouterReturnsNull`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "possibly-undefined-array-index"
message = "Possibly undefined array key `int(0)` accessed on `array<array-key, mixed>`."
count = 2

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "possibly-undefined-array-index"
message = "Possibly undefined array key `int(1)` accessed on `array<array-key, mixed>`."
count = 2

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testAddAppendsMiddlewareToEnd`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testCreateHandlerReturnsConfiguredRequestHandler`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testFluentInterface`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testPrependAddsMiddlewareToBeginning`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\Exception` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testAddAppendsMiddlewareToEnd`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\Exception` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testCreateHandlerReturnsConfiguredRequestHandler`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\Exception` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testPrependAddsMiddlewareToBeginning`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\ExpectationFailedException` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testAddAppendsMiddlewareToEnd`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\ExpectationFailedException` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testCreateHandlerReturnsConfiguredRequestHandler`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\ExpectationFailedException` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testFluentInterface`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\ExpectationFailedException` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testPrependAddsMiddlewareToBeginning`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\GeneratorNotSupportedException` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testAddAppendsMiddlewareToEnd`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\GeneratorNotSupportedException` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testPrependAddsMiddlewareToBeginning`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testAddAppendsMiddlewareToEnd`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testCreateHandlerReturnsConfiguredRequestHandler`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testFluentInterface`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testPrependAddsMiddlewareToBeginning`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testAddAppendsMiddlewareToEnd`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testCreateHandlerReturnsConfiguredRequestHandler`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testFluentInterface`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testPrependAddsMiddlewareToBeginning`.'
count = 1

[[issues]]
file = "tests/src/MiddlewareStackTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\UnknownClassOrInterfaceException` in `Waffle\Commons\Pipeline\Tests\MiddlewareStackTest::testCreateHandlerReturnsConfiguredRequestHandler`.'
count = 1

[[issues]]
file = "tests/src/RequestHandlerTest.php"
code = "mixed-method-access"
message = "Attempting to access a method on a non-object type (`mixed`)."
count = 1

[[issues]]
file = "tests/src/RequestHandlerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `Waffle\Commons\Pipeline\Tests\RequestHandlerTest::testHandlerIsImmutableAndReusable`.'
count = 1

[[issues]]
file = "tests/src/RequestHandlerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `Waffle\Commons\Pipeline\Tests\RequestHandlerTest::testItExecutesMiddlewareStackInOrder`.'
count = 1

[[issues]]
file = "tests/src/RequestHandlerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `Waffle\Commons\Pipeline\Tests\RequestHandlerTest::testMiddlewareCanShortCircuitThePipeline`.'
count = 1

[[issues]]
file = "tests/src/RequestHandlerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\ExpectationFailedException` in `Waffle\Commons\Pipeline\Tests\RequestHandlerTest::testItExecutesMiddlewareStackInOrder`.'
count = 1

[[issues]]
file = "tests/src/RequestHandlerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\ExpectationFailedException` in `Waffle\Commons\Pipeline\Tests\RequestHandlerTest::testMiddlewareCanShortCircuitThePipeline`.'
count = 1

[[issues]]
file = "tests/src/RequestHandlerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `Waffle\Commons\Pipeline\Tests\RequestHandlerTest::testHandlerIsImmutableAndReusable`.'
count = 1

[[issues]]
file = "tests/src/RequestHandlerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `Waffle\Commons\Pipeline\Tests\RequestHandlerTest::testItExecutesMiddlewareStackInOrder`.'
count = 1

[[issues]]
file = "tests/src/RequestHandlerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `Waffle\Commons\Pipeline\Tests\RequestHandlerTest::testMiddlewareCanShortCircuitThePipeline`.'
count = 1

[[issues]]
file = "tests/src/RequestHandlerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `Waffle\Commons\Pipeline\Tests\RequestHandlerTest::testHandlerIsImmutableAndReusable`.'
count = 1

[[issues]]
file = "tests/src/RequestHandlerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `Waffle\Commons\Pipeline\Tests\RequestHandlerTest::testItExecutesMiddlewareStackInOrder`.'
count = 1

[[issues]]
file = "tests/src/RequestHandlerTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `Waffle\Commons\Pipeline\Tests\RequestHandlerTest::testMiddlewareCanShortCircuitThePipeline`.'
count = 1
